// <auto-generated />
using EnglishDictionary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishDictionary.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    [Migration("20230401073311_Initialization")]
    partial class Initialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("EnglishDictionary.Models.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EnglishDictionary.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WordName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WordId");

                    b.HasIndex("WordTypeId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("EnglishDictionary.Models.WordExample", b =>
                {
                    b.Property<int>("ExampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExampleContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExampleId");

                    b.HasIndex("WordId");

                    b.ToTable("WordExamples");
                });

            modelBuilder.Entity("EnglishDictionary.Models.WordMeaning", b =>
                {
                    b.Property<int>("MeaningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeaningContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MeaningId");

                    b.HasIndex("WordId");

                    b.ToTable("WordMeanings");
                });

            modelBuilder.Entity("EnglishDictionary.Models.WordType", b =>
                {
                    b.Property<int>("WordTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WordTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WordTypeId");

                    b.ToTable("WordTypes");
                });

            modelBuilder.Entity("EnglishDictionary.Models.Word", b =>
                {
                    b.HasOne("EnglishDictionary.Models.WordType", "Type")
                        .WithMany()
                        .HasForeignKey("WordTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EnglishDictionary.Models.WordExample", b =>
                {
                    b.HasOne("EnglishDictionary.Models.Word", "Word")
                        .WithMany("WordExamples")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishDictionary.Models.WordMeaning", b =>
                {
                    b.HasOne("EnglishDictionary.Models.Word", "Word")
                        .WithMany("WordMeanings")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishDictionary.Models.Word", b =>
                {
                    b.Navigation("WordExamples");

                    b.Navigation("WordMeanings");
                });
#pragma warning restore 612, 618
        }
    }
}
